FROM node:lts

WORKDIR /usr/src/app

RUN yarn global add typescript
RUN yarn global add prisma

COPY ./package.json .

COPY ./yarn.lock .

RUN yarn install
RUN prisma generate

COPY . .


CMD [ "yarn", "test:watch" ]