name: "🐛 Bug report"
description: "File a bug/issue"
title: "bug: <title>"
labels: ["bug"]
body:
  - type: dropdown
    id: bug_type
    attributes:
      label: Project
      description: In which project this bug is located?
      options:
        - "Mobile app"
        - "Server"
        - "Core"
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: A concise description of what you are currently experiencing
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what is expected to happen
    validations:
      required: true
  - type: textarea
    id: steps_reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: false
  - type: textarea
    id: anything_else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
