name: "📝 Docs"
description: "Found a security issue report it here"
title: "[DOCS] :memo: <title>"
labels: [":memo: documentation"]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A concise description if you want us to update or create new documentation
      validations:
          required: false
    - type: textarea
      id: anything_else
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
