name: "🔒 Security Issue"
description: "Found a security issue report it here"
title: "[SECURITY] :lock: <title>"
labels: [":lock: security"]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: A concise description of the security issue
      validations:
          required: true
    - type: textarea
      id: how_to_solve
      attributes:
          label: How can we solve this
          description: Please tell us how can we solve this issue
      validations:
          required: false
    - type: textarea
      id: anything_else
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
